name: Test

on:
  push:
  pull_request:

env:
  SOURCE_API_URL: ${{ vars.SOURCE_API_URL }}
  TZ: ${{ vars.TZ }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Typecheck
        run: npm run typecheck
      - name: Run Tests
        run: npm run test
      - name: Build
        run: npm run build
